x <- seq(1, 5, by = 0.01)
y.upper <- sqrt((x^2-1)*3)
y.lower <- -sqrt((x^2-1)*3)
y.max <- max(y.upper)
y.min <- min(y.lower)
plot(c(-5, 5), c(y.min, y.max), type = "n", xlab = "x", ylab = "y")
lines(x, y.upper)
lines(-x, y.lower)
lines(-x, y.upper)
lines(x, y.lower)
x.s <- seq(-5,5, by = 0.01)
y.a1 <- sqrt(3)*x.s
lines(x.s,y.a1)
text(2, 8, "asymptote y = sqrt(3)*x")
lines(-x.s,y.a1)
points(2, 0)
points(-2,0)
text(2, 0, "focus (2, 0)", pos=4)
title("The hyperbola x^2 - y^2/3 = 1")
